### ISSUE TITLE
trigger fork after filter events using github token

### ISSUE THREAD

**Issue by smarlhens** [smarlhens/github-filter-npm-repos-to-empower#23]
```yml

jobs:
  fork-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Fork repository
      run: |
        curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ repository.owner }}/${{ repository.name }}/forks
```
